on: push
name: Test
jobs:
  jiraLogin:
    name: Jira Login
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Jira Login
      uses: ./
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
